# wrangler.toml
name = 'empty-boat-23ee'
main = "src/worker.js"
compatibility_date = "2026-04-21"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "apitest_bind"
database_name = "apitest"
database_id = "2dfcaa0c-1045-4b34-a6ea-a8da9fae6b58"
