# wrangler.toml
name = 'cf-pages-test'
main = "src/worker.js"
compatibility_date = "2026-04-21"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "apitest_bind"
database_name = "test"
database_id = "3c6c874e-0e2b-4532-add2-15bd521af2c7"
